import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { theme } from '../core/theme';
import { DynamicFormBuilder, FormRenderer, ApplicationStatusWizard } from '../components/NGOFormComponents';

export default function NGOFormsScreen({ navigation }) {
    const [viewMode, setViewMode] = useState('volunteer'); // 'admin' or 'volunteer'

    // Mock schema generated by the builder
    const mockFormSchema = [
        { label: 'Full Name', type: 'text', placeholder: 'Enter your name' },
        { label: 'Available Tools', type: 'multiple-choice', options: ['Shovel', 'Cement Bags', 'Gloves', 'None'] },
        { label: 'Upload ID Proof', type: 'photo' }
    ];

    return (
        <View style={styles.container}>
            <View style={styles.header}>
                <TouchableOpacity onPress={() => navigation.goBack()} style={{ paddingRight: 16 }}>
                    <Text style={{ fontSize: 24 }}>←</Text>
                </TouchableOpacity>
                <Text style={styles.headerTitle}>NGO Volunteer Forms</Text>
            </View>

            <View style={styles.toggleRow}>
                <TouchableOpacity
                    style={[styles.toggleBtn, viewMode === 'volunteer' && styles.toggleBtnActive]}
                    onPress={() => setViewMode('volunteer')}
                >
                    <Text style={[styles.toggleText, viewMode === 'volunteer' && styles.toggleTextActive]}>Volunteer View</Text>
                </TouchableOpacity>
                <TouchableOpacity
                    style={[styles.toggleBtn, viewMode === 'admin' && styles.toggleBtnActive]}
                    onPress={() => setViewMode('admin')}
                >
                    <Text style={[styles.toggleText, viewMode === 'admin' && styles.toggleTextActive]}>NGO Admin View</Text>
                </TouchableOpacity>
            </View>

            <ScrollView contentContainerStyle={styles.content}>
                {viewMode === 'volunteer' ? (
                    <View>
                        <Text style={styles.sectionHeading}>My Application Status</Text>
                        <ApplicationStatusWizard currentStep="Under Review" />

                        <Text style={[styles.sectionHeading, { marginTop: 24 }]}>Pothole Repair Application</Text>
                        <Text style={{ color: '#666', marginBottom: 16 }}>NGO: City Savers Org</Text>
                        <FormRenderer schema={mockFormSchema} />
                    </View>
                ) : (
                    <DynamicFormBuilder />
                )}
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F8F9FA' },
    header: { flexDirection: 'row', alignItems: 'center', padding: 16, paddingTop: 40, backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: '#EEE' },
    headerTitle: { fontSize: 20, fontWeight: 'bold' },
    toggleRow: { flexDirection: 'row', padding: 16, backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: '#EEE' },
    toggleBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
    toggleBtnActive: { borderBottomColor: theme.colors.primaryGreen },
    toggleText: { color: '#999', fontWeight: 'bold' },
    toggleTextActive: { color: theme.colors.primaryGreen },
    content: { padding: 16 },
    sectionHeading: { fontSize: 18, fontWeight: 'bold', marginBottom: 16, color: '#333' }
});
